name: Test
on:
  - push
  - pull_request

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Commit Check
        uses: https://github.com/IceflowRE/gitcc@e5b22543970609a3d60a2c39c77b244fadf3ef3b
        with:
          validator: "simpletag"
