name: Test
on:
  - push
  - pull_request

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Commit Check
        uses: IceflowRE/gitcc@ed6d2012bcb675d61d2ad947646d1a8253c0810b
        with:
          validator: "simpletag"
