name: Test
on:
  - push
  - pull_request

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Commit Check
        uses: IceflowRE/gitcc@43553f4fb47c3e2b56c79196be1ce74eb7d09125
        with:
          validator: "simpletag"
