name: Test
on:
  - push
  - pull_request

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Commit Check
        uses: IceflowRE/gitcc@5dde692e3c253f81aaf6b3ba42016565d49c7791
        with:
          validator: "simpletag"
